# Generated by Django 5.2.4 on 2025-07-19 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_description_post_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodWasteSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftovers_discarded', models.CharField(choices=[('Never', 'Never'), ('Rarely', 'Rarely'), ('Often', 'Often'), ('Always', 'Always')], max_length=20)),
                ('composts', models.BooleanField()),
                ('expiry_check', models.CharField(choices=[('Always', 'Always'), ('Sometimes', 'Sometimes'), ('Never', 'Never')], max_length=20)),
                ('meal_planning', models.CharField(choices=[('Every Week', 'Every Week'), ('Sometimes', 'Sometimes'), ('Never', 'Never')], max_length=20)),
                ('eat_out_before_clearing_fridge', models.CharField(choices=[('Always', 'Always'), ('Sometimes', 'Sometimes'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
