# Generated by Django 5.2.4 on 2025-07-19 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_foodwastesurvey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterConservationSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('short_showers', models.CharField(max_length=20)),
                ('tap_off_while_brushing', models.BooleanField()),
                ('washing_machine_load', models.CharField(max_length=20)),
                ('water_efficient_appliances', models.BooleanField()),
                ('rainwater_usage', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
