# Generated by Django 5.2.4 on 2025-07-19 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_waterconservationsurvey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprintSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_mode', models.CharField(choices=[('car', 'Car'), ('transit', 'Public Transit'), ('bike_walk', 'Walk/Bike')], max_length=20)),
                ('diet_type', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('mixed', 'Mixed'), ('meat_heavy', 'Meat-heavy')], max_length=20)),
                ('electricity_usage', models.CharField(choices=[('low', 'Low (<200 kWh/month)'), ('medium', 'Medium (200-500 kWh/month)'), ('high', 'High (>500 kWh/month)')], max_length=20)),
                ('flight_frequency', models.CharField(choices=[('none', 'None'), ('few', '1-3 per year'), ('frequent', '4+ per year')], max_length=20)),
                ('shopping_habits', models.CharField(choices=[('rare', 'Rare'), ('occasional', 'Occasional'), ('frequent', 'Frequent')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
